abbr -ag ga 'git add'
abbr -ag gaa 'git add --all'
abbr -ag gc 'git commit -v'
abbr -ag gc! 'git commit -v --amend'
abbr -ag gca 'git commit -v -a'
abbr -ag gca! 'git commit -v -a --amend'
abbr -ag gco 'git checkout'
abbr -ag gd 'git diff'
abbr -ag ggfl 'git push --force-with-lease origin (_git_branch_name)'
abbr -ag ggl 'git pull origin (_git_branch_name)'
abbr -ag ggp 'git push origin (_git_branch_name)'
abbr -ag ggsup 'git branch --set-upstream-to=origin/(_git_branch_name)'
abbr -ag ggu 'git pull --rebase origin (_git_branch_name)'
abbr -ag gl 'git pull'
abbr -ag glo 'git log --oneline --decorate'
abbr -ag glol "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
abbr -ag gp 'git push'
abbr -ag gpsup 'git push --set-upstream origin (_git_branch_name)'
abbr -ag grb 'git rebase'
abbr -ag grba 'git rebase --abort'
abbr -ag grbc 'git rebase --continue'
abbr -ag grbi 'git rebase -i'
abbr -ag grst 'git restore --staged'
abbr -ag gst 'git status'
abbr -ag gsw 'git switch'
abbr -ag gswc 'git switch -c'
